### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by mindriot101** [rust-tutorials/learn-luminance#20]
The `builder-pattern` link is missing in chapter 2.1:

https://github.com/rust-tutorials/learn-luminance/blame/88a213ea3d07bfd812d7fb05b21eacb5bdfc753c/src/chapter_2_1.md#L168

I would submit a PR correcting this if I knew what link the author wanted.

**Comment by phaazon** [comment]
Oh, it’s a link to the type in the docs.rs/luminance documentation that is missing. Thanks for reporting.

**Comment by mindriot101** [comment]
That's ok, would you like me to close the issue or leave it open until it's resolved?

**Comment by phaazon** [comment]
Leave it open, I’ll fix it. :)
